### PR TITLE
5pm-3-switch basic search and search by course number from a hard coded list of subjects to use selectSubject.

### PR DESCRIPTION
**Pull request by chucklesbao**
Previously when users wanted to select a subject on both the basic search and search by course number, they only had the option to search from a list of hard coded subjects. We implemented the selectSubject for both of these searches so users will now have a complete catalog of subjects to search from. 

- Basic search will only work for CMPSC and MATH because the backend is not working for other subjects.

### CODE REVIEW

**Review by squirmel — DISMISSED** [review]
LGTM

**Review by squirmel — APPROVED** [review]
LGTM

**Review by thaophan1 — APPROVED** [review]
LGTM, amazing merge conflict resolution

**Review by brian-w-ai — APPROVED** [review]
LGTM

**Review by mknguyen1202 — APPROVED** [review]
LGTM, the refactoring works!

**Review by mara-downing — APPROVED** [review]
LGTM

**Pull request merged**
