### PR TITLE
5pm-3 KDBCT Added code to save Quarter/Subject on (broken) basic search so that user selections will remain the same when they return to the site.

### PR DESCRIPTION
**Pull request by mknguyen1202**
User selection for quarter and subject on the secondary/broken basic search page will now be saved in local storage meaning that the next time they return to the basic search page after leaving/closing the page, their previous choices will remain. This works with refreshes, returning from another page on the website, and closing and reopening the website entirely.

### CODE REVIEW

**Review by chucklesbao — DISMISSED** [review]
LOOKS GOOD TO ME!!!!!

**Review by squirmel — DISMISSED** [review]
LGTM!

**Review by brian-w-ai — APPROVED** [review]
L G T M

**Review by thaophan1 — APPROVED** [review]
LGTM

**Review by pconrad — CHANGES_REQUESTED** [review]
This PR title and PR description doesn't really capture what this does from a user standpoint.

Please rewrite the title and the description so that someone looking at this PR knows what the impact is on the end user.

Users searching for courses don't know what getters and setters are, and they don't care. What they do care about is the functionality that this change, if implemented properly, provides for them.

What is that?  What is different before and after this PR is implemented?

**Pull request closed without merging**
