### PR TITLE
IG EY - Fixed the red and yellow colors for courses search and factored out color definitions.

### PR DESCRIPTION
**Pull request by isaiahgama**
Updated yellow and red colors for courses BasicCourseTable and CourseLegend. Factored out color definitions into a common file that can be imported from utils

### CODE REVIEW

**Review by WadeVaresio — APPROVED** [review]
LGTM. Make sure to get a code review from a team member who did not work on this issue.

**Review by khoang1800 — APPROVED** [review]
The changes look right to me.

**Review by mattbhahn — APPROVED** [review]
LGTM

**Review by shethon123 — APPROVED** [review]
LGTM

**Pull request merged**
