### PR TITLE
Deploy New Favicon with Storke Image Kevin Sheldin

### PR DESCRIPTION
**Pull request by shethon123**
In this pull request, we modify index.html to use the new favicon.ico image.

### CODE REVIEW

**Review by btk5h — DISMISSED** [review]
Please do not remove the sample files from the repo. Can you revert those deletions?

**Review by khoang1800 — APPROVED** [review]
All changes are included and the env.local.SAMPLE file is back. LGTM

**Review by WadeVaresio — APPROVED** [review]
LGTM

**Review by isaiahgama — COMMENTED** [review]
LGTM

**Review by isaiahgama — APPROVED** [review]
LGTM

**Review by ericyuan915 — APPROVED** [review]
LGTM

**Review by mattbhahn — APPROVED** [review]
LGTM

**Pull request merged**
