### PR TITLE
5pm-2 sa - made navbar smaller

### PR DESCRIPTION
**Pull request by sriya112**
- made the UCSB Courses Search icon smaller
- moved the UCSB Courses Search text to the right
- styled the text to be white and have a little bit of space from the next right element
- linked the text to the Home Page as well
- moved headers down to fit better in the new navbar

### CODE REVIEW

**Review by Christine-ong — APPROVED** [review]
LGTM

**Review by sydneylim — APPROVED** [review]
LGTM

**Review by 320trankt — APPROVED** [review]
LGTM

**Review by Christine-ong — APPROVED** [review]
LGTM

**Review by mmunozvaltierra — APPROVED** [review]
LGTM

**Review by WadeVaresio — APPROVED** [review]
LGTM, tested on Heroku, looks good!

**Pull request merged**
