### PR TITLE
5pm-3 KDBCT Added code to save Quarter/Subject on  Search->Basic Search page so that user selections will remain the same when they return to the site.

### PR DESCRIPTION
**Pull request by chucklesbao**
User selection for quarter and subject on the search->basic search page will now be saved in local storage meaning that the next time they return to the basic search page after leaving/closing the page, their previous choices will remain. This works with refreshes, returning from another page on the website, and closing and reopening the website entirely. This is so that users don't need to reselect fields that they previously selected.

### CODE REVIEW

**Comment by chucklesbao** [comment]
Updated with Thao's code from issues 281. Ready to merge

**Review by thaophan1 — APPROVED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM, pending test on qa

**Review by squirmel — APPROVED** [review]
Looks very good to me, just checked the functionality of this branch running locally

**Review by squirmel — APPROVED** [review]
LGTM

**Review by thaophan1 — APPROVED** [review]
LGTM

**Pull request merged**
