### PR TITLE
az/lw 5pm-1 Implemented get, new, delete methods for scheduleItem

### PR DESCRIPTION
**Pull request by alanzhang052**
Uncommented and correctly implemented the get, new, delete methods under `ScheduleItemController.java`

We ultimately decided not to touch the getByScheduleId and deleteByScheduleId methods because it was irrelevant to our next issues. To add on, we saw there were other methods that needed to be built on top of getByScheduleId and deleteByScheduleId such as findOneByQuarterAndCourseId in `ArchivedCourseRepository` and findByScheduleId in `ScheduleItemRepository`.

### CODE REVIEW

**Review by JacquelineMai — DISMISSED** [review]
I'm not sure why so much of the original file was commented out, but we'd prefer not to have large blocks of commented code in the PRs, since it just adds dead code. If you're not implementing those functions for this PR, go ahead and take them out.

I also noticed this PR is failing codecov- since you added several new functions into the code base, they need to have corresponding tests. You might look at the existing tests for the other controllers as a reference for how to get started, and definitely ask us if you have any questions about it.

**Review by markoristicc — APPROVED** [review]
LGTM!

**Review by mara-downing — APPROVED** [review]
LGTM

**Comment by pconrad** [comment]
Estimated at 20 points

**Pull request merged**
