### PR TITLE
5pm-3 TP - Added QuarterSelector for every Search Page

### PR DESCRIPTION
**Pull request by thaophan1**
## User Story
As a user, I can now select Quarters starting from Fall 2008 to Fall 2021 on every page under the Search tab. Now, the user can see a larger list of history of courses.

## Main Changes
Updated Search/courseNumber and Search/GE to use quarterRange function and SelectQuarter component to generate a list of quarters starting from Fall 2008 to Fall 2021, instead of the previously hard coded list.
Updated Search/instructor to generate a list of quarters from Fall 2008 to Fall 2021 instead of Winter 2008 to Summer 2020 to be more consistent with the rest of the Search pages

## Test Checklist
- [x] Local all Maven tests passed
- [x] Local all javascript tests and test suites passed
- [x] GitHub Actions passed
- [x] Website loads and works locally
- [x] Branch is deployed

## Files Changed
javascript/src/main/component/BasicCourseSearch/CourseSearchCourseStartEndQrt.js
javascript/src/main/component/BasicCourseSearch/CourseSearchFormInstructor.js
javascript/src/main/component/BasicCourseSearch/GECourseSearchForm.js

### CODE REVIEW

**Review by chucklesbao — DISMISSED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM... will merge pending a deployment to test it interactively.

**Review by squirmel — APPROVED** [review]
LGTM after testing locally

**Review by chucklesbao — APPROVED** [review]
LOOKS GOOD TO ME

**Review by brian-w-ai — APPROVED** [review]
LGTM

**Review by mknguyen1202 — APPROVED** [review]
LGTM

**Review by JacquelineMai — APPROVED** [review]

**Pull request merged**
