### PR TITLE
sl - 5pm-2 - Remove Course JSON Response from all search pages

### PR DESCRIPTION
**Pull request by sydneylim**
Removed the Course JSON Response card from the bottom of all course searches completely, regardless of whether there are results are not, as it does not add to the user experience.

### CODE REVIEW

**Review by JacquelineMai — CHANGES_REQUESTED** [review]
I'd suggest removing the JSONPrettyCard component itself from the pages that are currently using it (the `Home.js` file, for example), rather than just removing the contents of these files. With the approach you have here, the component will still be added to the pages, but it just won't contain anything. This will technically work to remove the visible button from the page, but it leaves a lot of dead code both here and on the pages that are using the component.

**Review by 320trankt — APPROVED** [review]
LGTM, although with complete removal of all JSONPrettyCard components we could consider just deleting the class definition under javascript/src/main/components/utilities as well if we are not going to use the class again, though that would likely be brought up in another issue/be up to the professor.

**Review by Christine-ong — APPROVED** [review]
LGTM

**Review by sriya112 — DISMISSED** [review]
LGTM

**Review by mmunozvaltierra — APPROVED** [review]
LGTM

**Review by andrewhlu — DISMISSED** [review]
> LGTM, although with complete removal of all JSONPrettyCard components we could consider just deleting the component definition under javascript/src/main/components/utilities as well if we are not going to use the component again, though that would likely be brought up in another issue/be up to the professor.

Talked to @btk5h, we both think that the component (and its associated story) should be removed entirely. Can you make this change?

**Review by JacquelineMai — APPROVED** [review]
lgtm

**Review by Christine-ong — APPROVED** [review]
LGTM

**Review by 320trankt — APPROVED** [review]
LGTM

**Pull request merged**
