### PR TITLE
5pm-3 Refactor BasicCourse Level

### PR DESCRIPTION
**Pull request by mknguyen1202**
In this PR, we create our own SelectLevel Component and replace the form with the component in BasicCourseFormSearch.
The SelectLevel component also supports local storage to save the chosen item so that every time the user go to another page or refresh the site, the previous value they selected will be remembered and used.

## user story
As a user, the selected value is stored and reused so that after I go the next end point or refresh the page, I can still see the value I chose previously.

## developer story
As a developer, I can reuse the component to make the overall code more maintainable and usable.

### CODE REVIEW

**Review by thaophan1 — APPROVED** [review]
LGTM

**Review by squirmel — APPROVED** [review]
LGTM after testing locally

**Review by chucklesbao — APPROVED** [review]
Looks GOOD TO me?

**Review by mara-downing — APPROVED** [review]
LGTM

**Pull request merged**
