### PR TITLE
5pm 3 refactor csv download code on home page

### PR DESCRIPTION
**Pull request by brian-w-ai**
In this PR,  we refactored the CSV download button implementation on the Home Page and Basic Courses Search page to use the button built into React Bootstrap Table 2. The implementations now matches the ones used in the other three searches (ie GE search, by course number, and by instructor). 

From a user's perspective, the CSV files downloaded now all follow a consistent format and contain all the information from the user's search. The previous implementations resulted in the CSV files only having courseID, course name, and number of units. The refactored one now also includes the section, section times, enroll codes, etc.

### CODE REVIEW

**Review by squirmel — APPROVED** [review]
LGTM I like the improved features

**Review by thaophan1 — APPROVED** [review]
LGTM, loving the new features

**Review by mknguyen1202 — APPROVED** [review]
LGTM

**Review by mara-downing — APPROVED** [review]
LGTM

**Review by chucklesbao — APPROVED** [review]
LOOKS GOOD to ME!

**Pull request merged**
