### PR TITLE
5pm-2 CO List times in 12 hour format by incorporating a third-party date formatter

### PR DESCRIPTION
**Pull request by Christine-ong**
Incorporated moment.js to format time and reduce code from previous issue #235 + fixes bug #342 (null value for time).

### CODE REVIEW

**Review by sydneylim — APPROVED** [review]
LGTM

**Review by 320trankt — APPROVED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM, and tested on QA

**Comment by pconrad** [comment]
20 points for incorporating moment.js, and 10 points for fixing the bug with null times.

**Pull request merged**
