### PR TITLE
mm/sa 5pm-2 - Remove Jumbotron tags in TableLegend.js

### PR DESCRIPTION
**Pull request by sriya112**
In this PR, as a user I can see less empty space around the guide for which color means full/almost full/etc. so that the page is more compact.

### CODE REVIEW

**Review by 320trankt — APPROVED** [review]
LGTM

**Review by JacquelineMai — CHANGES_REQUESTED** [review]
Looks like this PR has some merge conflicts with the main branch, which will have to be resolved before CI can run and this code can be merged. You'll need to do a `git pull` locally, which will likely give you a message saying there are merge conflicts. Once you've done that, you should be able to open the `TableLegend.js` file and see the conflicts indicated there, resolve them locally, then commit and push. 

You can also see the conflicts in the web editor here https://github.com/ucsb-cs156-s21/proj-ucsb-courses-search/pull/272/conflicts. Please try to avoid making any actual changes in the web editor, though, since it's bad practice and could potentially lead to more merge conflicts later on if you don't pull locally.

Ask the staff if you have any questions or want any help with this!

**Review by JacquelineMai — APPROVED** [review]
LGTM

**Review by sydneylim — APPROVED** [review]
LGTM

**Review by Christine-ong — APPROVED** [review]
LGTM

**Pull request merged**
