### PR TITLE
5pm-3 Refactor In SelectQuarter Component using localStorage277 

### PR DESCRIPTION
**Pull request by mknguyen1202**
In this PR, we modify the SelectQuarter component to save the selected value in local storage.  This means that on any page where this component is used, the first time users visit the page the default quarter will be the first in the list, but on subsequent visits, the previous value they selected will be remembered and used.

The point is to convey what the user will experience as a result of this change.

### CODE REVIEW

**Review by squirmel — APPROVED** [review]
lgtm

**Review by chucklesbao — APPROVED** [review]
Looks ok to me!

**Review by thaophan1 — APPROVED** [review]
LGTM

**Review by mara-downing — APPROVED** [review]
LGTM

**Pull request merged**
